[package]
name = "libxml2-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
workspace_root = "0.2"
ctor = "0.5"
serial_test = "3.2"

[build-dependencies]
bindgen = "0.72"
cmake = "0.1"
