name: Test Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install libxml2 (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          vcpkg install libxml2
          vcpkg integrate install
          echo "CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
          Get-ChildItem -Include parser.h -File -Recurse
          Get-ChildItem env:

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
